### ISSUE TITLE
Tab and Space

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/sputnikvm#17]
Right now in the rust code there's some mixes of tab and space for indentation. This creates some confusion for my editor. Do we have a style guide for this? Or should we just lint the code to always use space?

**Comment by sjmackenzie** [comment]
train your editor to follow the root `.editorconfig` file. There is also a styleguide in the root `GUIDE.md`.

**Comment by sorpaas** [comment]
Thanks!

Also, I found in the style guide:

```
Use spaces, not tabs.
```

So probably let's lint the code?

**Comment by sjmackenzie** [comment]
Hmm that mix could have come about before I added the styleguide and .editorconfig. 

"lint the code" <- in the .editorconfig, so it'll highlight tabs? Sure! Great idea.

**Comment by sjmackenzie** [comment]
I want to avoid using tools like `rustfmt` which make it harder to catch code smell.
