### ISSUE TITLE
Problem: don't know the best way to test the evm

### ISSUE THREAD

**Issue by sjmackenzie** [ethereumproject/sputnikvm#19]
### Potential solution # 1:

* build an executable like `ethereumclassic/gaslighter`

##### behaviour common between `dev` and `ci` mode
* reads a clone of `ethereumclassic/tests` every time `gaslighter` is called and depending on the arguments to `gaslighter` the relative test in `ethereumclassic/tests` is called. e.g. 
```
$ gaslighter dev sputnikvm --path <path/to/sputnikvm> --test hierarchical_name_to_test_in_ethereumclassic/tests channel --sockets tcp://localhost:1920
```
* `gaslighter` supports different methods of connecting `channel --socket tcp://localhost:1920 --sharedobject <path> --cli <path> --crate <path>` arguments. (still thinking about the `crate` argument as Rust has no ABI). Thus allowing the tests to be run over those channels
##### `dev` mode:
* `gaslighter` calls cargo and compiles `sputnikvm` every time `gaslighter` is called.
* `gaslighter` becomes the primary means to compile `sputnikvm` when in development mode.
* `gaslighter` could accept other params like `geth` `parity` and reproduce the same test against those vms.

##### `CI` mode:
* `gaslighter` doesn't compile `sputnikvm` if in CI mode. `nix` will ensure this is done with exact dependencies. 
*  the full battery of tests will be run against the compiled `sputnikvm` artefact. Which (will later) include fuzzy tests etc.
#### pros
* convenient to fire off xyz test as you're developing certain parts of the vm
* add new tests to the ethereumclassic/tests repo
* `gaslighter` can now become the CI test bootstrapper to be run by upon each pull request.
* becomes a testbed to put fuzzy testing and other fancy techniques.

#### cons
* too much overhead and could easily be described as unit tests in `sputnikvm`, taking this path means we have no `gaslighter` executable to test other vms.

### extra work

* convert the entire ethereumproject/tests into human readable format  i.e.
```
PUSH
MLOAD
GAS
JUMPDEST
etc
```
instead of [this](https://github.com/ethereumproject/tests/blob/develop/VMTests/vmtests.json#L41)

@sorpaas any opinions?

### Potential solution # 2

Keep the above functionality and add a new build artefact to sputnikvm called `gaslighter`. Other ethereum vms will need to clone `sputnikvm` if they want to use `gaslighter`. Secondly this now enables us to test the `crate` option.

**Comment by sorpaas** [comment]
I think solution # 1 would be the ultimate goal -- it looks elegant and enables many testing techniques. However, I would worry that it's a lot of work especially when right now we haven't finished the essential of EVM... So it might be a good idea to do # 2 first and then gradually move to # 1 when we have time. What do you think?

For `convert the entire ethereumproject/tests into human readable format`, my concern is that most EVM code would be compiled from higher-level languages. As a result, even we make it human readable, it might not help us to understand the test... However, I do think this is useful for short EVM programs -- only a few lines probably. Besides, this is not hard to implement -- some string replacement would do. So I would suggest to implement both and use the one that seems appropriate for different tests. How about this?

**Comment by sjmackenzie** [comment]
Yes exactly, no 2. 
It will be difficult to test crate fuctionality (unless we use `nixcrates`) if we go down path 1.
Anyway, I think we've found the right balance!
